name: Generate Changelog & Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.0.5)'
        required: true
        type: string
      version_prev:
        description: 'Previous Version number (e.g., 1.0.5)'
        required: true
        type: string

jobs:
  changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
      issues: read
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Generate changelog
        id: changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sinceTag: ${{ github.event.inputs.version_prev }}
          futureRelease: ${{ github.event.inputs.version }}
          pullRequests: true
          prWoLabels: false
          issues: true
          issuesWoLabels: false
          filterByMilestone: false
          author: true
          unreleased: false
          breakingLabel: '### Breaking Changes'
          enhancementLabel: '### Enhancements'
          bugsLabel: '### Bug Fixes'
          deprecatedLabel: '### Deprecated'
          removedLabel: '### Removed'
          securityLabel: '### Security'
          issuesLabel: '### Issues'
          prLabel: '### Pull Requests'
          addSections: '{"documentation":{"prefix":"### Documentation","labels":["documentation"]},"feature":{"prefix":"### Features","labels":["feature"]}}'

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.event.inputs.version }}
          tag_name: ${{ github.event.inputs.version }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
