name: Release
on:
  workflow_dispatch:
    inputs:
      new_tag:
        description: 'New Tag'
        required: true  
      prev_tag:
        description: 'Prev Tag'
        required: true  

jobs:
  changelog:
    name: Update changelog
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code" 
        uses: actions/checkout@v3
        with:
          ref: master
      - name: "Generate full changelog"
        id: generate_changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 
          output: CHANGELOG.md
          futureRelease: ${{ github.event.inputs.new_tag }}
          dateFormat: "%m/%d/%Y"
          simpleList: true
      - name: Commit changes
        id: commit_changelog
        timeout-minutes: 1
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update CHANGELOG.md'
          branch: master
      - name: "Generate new changelog"
        id: generate_changelog_partial
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 
          output: UPDATES.md
          futureRelease: ${{ github.event.inputs.new_tag }}
          dateFormat: "%m/%d/%Y"
          simpleList: true
          sinceTag: ${{ github.event.inputs.prev_tag }}
      - name: Extract new changes
        id: extract_change
        run: echo ::set-output name=changelog::$(cat UPDATES.md | awk NF | head -n -1 | tail -r | head -n -2)
      - uses: avakar/tag-and-release@v1
        with:
          tag_name: ${{ github.event.inputs.new_tag }}
          body: ${{steps.extract_change.outputs.changelog}}
          commit: ${{ steps.commit_changelog.outputs.commit_sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# CHANGELOG=$(cat CHANGELOG.md | grep -E '${{ github.event.inputs.prev_tag }}.*${{ github.event.inputs.new_tag }}' -A4)
